# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/173LpPLZ85eCZGSIF4uZgMTgwyR9_Nxx3
"""

#https://programmers.co.kr/learn/courses/30/lessons/12949

import numpy as np

def solution(arr1, arr2):
    an = np.dot(arr1,arr2)
    answer = an.tolist()
    return answer

def solution(arr1, arr2):
    answer = []
    new_arr2 = list(map(list,zip(*arr2)))
    
    for i in arr1:
        an = []
        for j in new_arr2:
            an.append(sum([x*y for x,y in zip(i,j)]))
        answer.append(an)
    
    return answer