# -*- coding: utf-8 -*-
"""6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6qIFUnzPaq-ygzvZsT9aDNQv9-SDJMD
"""

#https://programmers.co.kr/learn/courses/30/lessons/12924

import math

def solution(n):
    answer = 0
    
    for k in range(int(math.sqrt(1+8*n)/2)):
        a = (2*n/(k+1)-k)/2
        if a.is_integer() and a > 0:
            answer += 1

    return answer