# -*- coding: utf-8 -*-
"""7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-8g2dPaXMZLpsypV15Wrwxa4Ouies6U7
"""

#https://programmers.co.kr/learn/courses/30/lessons/12941

def solution(A,B): 
    A = sorted(A)
    B = sorted(B,reverse = True)
    answer = sum([a*b for a,b in zip(A,B)])
    return answer