# -*- coding: utf-8 -*-
"""9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fiK43K2o136caBJCfBinBa5qzvM9mjRy
"""

#https://programmers.co.kr/learn/courses/30/lessons/12909

def solution(s):
    num_l = s.count('(')
    num_r = s.count(')')
    l = 0
    r = 0

    if s[0] == ')' or s[-1] == '(':
        answer = False
    else:
        if num_l == num_r:
            for i in s:
                if i == '(':
                    l += 1
                else:
                    r += 1
                if l < r:
                    answer = False
                    break
                else:
                    answer = True
        else:
            answer = False
            
    return answer

def solution(s):
    while True:
        new_s = s.replace('()','',1)
        if new_s == s:
            break
        s = new_s 
    if s == '':
        answer = True
    else:
        answer = False
 
    return answer