# -*- coding: utf-8 -*-
"""10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1acceTsxQAXV9GUbmCbNlh4twdxn6nFsk
"""

#https://programmers.co.kr/learn/courses/30/lessons/17687

def solution(n, t, m, p):
    answer = ''
    arr_num_n = '0'
    a = 1
    num = [10,11,12,13,14,15]
    word = ['A','B','C','D','E','F']

    while True:
        copy_a = a
        num_n = ''

        while copy_a > 0:
            remainder = copy_a % n
            if remainder in num:
                remainder = word[remainder-10]
            num_n += str(remainder)
            copy_a = copy_a // n

        num_n = num_n[::-1]

        arr_num_n += num_n
        a += 1
        if len(arr_num_n) >= m*(t-1)+p:
            break

    for i in range(t):
        answer += arr_num_n[m*i+(p-1)]
            
    return answer