# -*- coding: utf-8 -*-
"""11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWf_CB9cf8WMByRE1cLnZb1ed-Gg4qHZ
"""

#https://programmers.co.kr/learn/courses/30/lessons/60057

def solution(s):
    
    def num(n):
        li = []
        for i in range(0,len(s),n):
            li.append(s[i:i+n]) 
        li.append(0)
        an = []
        k = 1
        for i in range(len(li)-1):
            if li[i] != li[i+1]:
                an.append(li[i])
                k = 1
            else:
                k += 1
                an = list(an)
                an.append(k)
                if k > 2:
                    an.pop(len(an)-2)

        an = ''.join(map(str,an))
        return len(an)

    if len(s) != 1:
        li_n = list(i for i in range(1,int(len(s)/2)+1))
    else:
        li_n = [1]
        
    li_num = []
    for i in li_n:
        li_num.append(num(i))

    answer = min(li_num)

    return answer