# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuXsXwUunPsNa5mcIpb1MnQjTYev3rm_
"""

#https://programmers.co.kr/learn/courses/30/lessons/1845

def solution(nums):
    answer = 0
    unique = len(set(nums))
    if unique < len(nums)/2:
        answer = unique
    else:
        answer = int(len(nums)/2)
    return answer