# -*- coding: utf-8 -*-
"""11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EOctaLrB0elEdYxU9U0b73WqfprrYk1q
"""

#https://programmers.co.kr/learn/courses/30/lessons/70128

def solution(a, b):
    answer = 0
    for i in range(len(a)):
        answer += a[i]*b[i]
    return answer