# -*- coding: utf-8 -*-
"""19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gfmA34ArdXC1SdBt15HfJKm0YWUK-jwf
"""

#https://programmers.co.kr/learn/courses/30/lessons/68644

from itertools import combinations as cb

def solution(numbers):
    answer = []
    
    for i in list(cb(numbers,2)):
        answer.append(sum(i))   
    
    answer = sorted(list(set(answer)))
    return answer