# -*- coding: utf-8 -*-
"""23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdyYeyyDQn2LhBlyEO_zGz0gSGd87emL
"""

#https://programmers.co.kr/learn/courses/30/lessons/12910

def solution(arr, divisor):
    answer = []
    
    for i in arr:
        if i % divisor == 0:
            answer.append(i)
    
    if len(answer) == 0:
        answer.append(-1)
    
    answer = sorted(answer)
    return answer