# -*- coding: utf-8 -*-
"""27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBQxTBDjSLnDSGUmpHz-BU82zwTjFAH7
"""

#https://programmers.co.kr/learn/courses/30/lessons/12917

def solution(s):
    answer = ''
    li_s = sorted(s,reverse = True)
    for i in li_s:
        answer += i
    return answer