# -*- coding: utf-8 -*-
"""30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18LnqHxDVGNjOC50JUNJ9DNgk-vCUpl4W
"""

#https://programmers.co.kr/learn/courses/30/lessons/12921

def solution(n):
    li_num = [1 for i in range(n+1)]
    for i in range(2,n+1):
        if li_num[i] == 1:
            a = 2
            while i*a <= n:
                li_num[i*a] = 0
                a += 1
    answer = sum(li_num)-2
    return answer

# 에라토스테네스의 체 이용한 알고리즘