# -*- coding: utf-8 -*-
"""32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrH8xVbJXdk2TBXX5tKq_vvDRao1rmRT
"""

#https://programmers.co.kr/learn/courses/30/lessons/12925

def solution(s):
    answer = int(s)
    return answer