# -*- coding: utf-8 -*-
"""33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k5jdt-VCmc0SuCTVBQwvstqFu93Ikqfb
"""

def solution(s, n):
    answer = ''
    for i in s:
        if i == " ":
            answer += i
        else:
            num = ord(i)
            if num <= 90:
                num += n
                if num > 90:
                    answer += chr(64+num%90)
                else:
                    answer += chr(num)
            elif num >= 97:
                num += n
                if num > 122:
                    answer += chr(96+num%122)
                else:
                    answer += chr(num)
    return answer