# -*- coding: utf-8 -*-
"""001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-srt5-CH87e8ml1ITh3eGGnleCx6CXj
"""

#https://school.programmers.co.kr/learn/courses/30/lessons/12938

def solution(n, s):
    q_li=[]

    if n > s:
        q_li = [-1]
    else:
        q = s // n 
        r = s % n
        q_li = [q]*n
        
        for i in range(r):
            q_li[i] += 1
            
        q_li.sort()
        
    answer = q_li
    return answer